import { resolve } from 'node:path';
import { test, expect, login, seed } from './fixture';

test('location photos work without the tree and preserve the unsaved record while uploading', async ({ page }) => {
  await login(page);
  const projectId = seed().projectId;
  const created = await page.request.post(`/api/projects/${projectId}/records`, { headers: { origin: new URL(page.url()).origin }, data: { subtype: 'task', title: 'Location photo check' } });
  expect(created.status()).toBe(201);
  const record = await created.json();
  const path = `/projects/${projectId}/records/${record.id}`;
  await page.goto(path);
  await page.getByRole('button', { name: 'Edit record', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).fill('Unsaved title survives upload');
  await page.getByRole('textbox', { name: 'Location Notes', exact: true }).fill('Πίσω από το μπάνιο. Follow the marked edge.');
  const photos = page.getByRole('region', { name: 'Location photos', exact: true });
  await photos.getByLabel('Files', { exact: true }).setInputFiles([
    resolve('tests/browser/fixtures/media-oriented.jpg'),
    resolve('tests/browser/fixtures/media-synthetic.heic'),
  ]);
  await expect(photos.getByLabel('Photo phase', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Save record', exact: true })).toBeDisabled();
  await photos.getByRole('button', { name: 'Upload location photos', exact: true }).click();
  await expect(photos.locator('.photo-thumbnail')).toHaveCount(2);
  await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Unsaved title survives upload');
  await expect(page.getByRole('textbox', { name: 'Location Notes', exact: true })).toHaveValue('Πίσω από το μπάνιο. Follow the marked edge.');
  await photos.locator('.photo-thumbnail').first().click();
  await expect(page.locator('dialog img')).toBeVisible();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Unsaved title survives upload');
  await photos.getByRole('button', { name: 'Edit photo', exact: true }).first().click();
  await page.locator('dialog').getByLabel('Caption', { exact: true }).fill('Exact edge of planter');
  await expect(page.locator('dialog').getByLabel('Photo phase', { exact: true })).toHaveCount(0);
  await page.locator('dialog').getByRole('button', { name: 'Save evidence', exact: true }).click();
  await expect(page.locator('dialog')).toHaveCount(0);
  await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Unsaved title survives upload');
  await page.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Unsaved title survives upload', exact: true })).toBeVisible();
  await expect(page.getByText('Πίσω από το μπάνιο. Follow the marked edge.', { exact: true })).toBeVisible();
  const saved = await (await page.request.get(`/api/projects/${projectId}/records/${record.id}`)).json();
  expect(saved.locationIds).toEqual([]);
  await page.getByRole('button', { name: 'Photos & files', exact: true }).click();
  await expect(page.locator('.photo-thumbnail')).toHaveCount(0);
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  page.once('dialog', dialog => dialog.accept());
  await photos.getByRole('button', { name: 'Delete photo', exact: true }).first().click();
  await expect(photos.locator('.photo-thumbnail')).toHaveCount(1);
  const origin = new URL(page.url()).origin;
  const base = `/api/projects/${projectId}/records/${record.id}`;
  expect((await page.request.post(base + '/transitions', { headers: { origin }, data: { to: 'open' } })).status()).toBe(200);
  const link = await (await page.request.post(base + '/share-links', { headers: { origin }, data: { label: 'Location guide' } })).json();
  const shared = await page.context().newPage();
  await shared.setViewportSize({ width: 390, height: 844 });
  await shared.goto(link.url);
  await shared.getByRole('combobox', { name: 'Γλώσσα', exact: true }).selectOption('en');
  await expect(shared.getByRole('region', { name: 'Location photos', exact: true }).locator('.photo-thumbnail')).toHaveCount(1);
  await expect(shared.getByText('Πίσω από το μπάνιο. Follow the marked edge.', { exact: true })).toBeVisible();
  await expect(shared.getByRole('button', { name: 'Upload location photos', exact: true })).toHaveCount(0);
  await expect(shared.getByRole('button', { name: 'Delete photo', exact: true })).toHaveCount(0);
  expect(await shared.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await shared.route('**/api/shared/photos/*/display', route => route.fulfill({ status: 404, json: { error: 'not_available' } }));
  await shared.locator('.photo-thumbnail').click();
  await expect(shared.getByRole('alert')).toBeVisible();
  await expect(shared.locator('dialog')).toHaveCount(0);
  await expect(shared.getByRole('region', { name: 'Location photos', exact: true })).toHaveCount(0);
  await shared.close();
  await page.goto(path + '/print');
  await expect(page.getByRole('button', { name: 'Print / Save PDF', exact: true })).toBeEnabled();
  await expect(page.locator('.print-sheet')).toContainText('Πίσω από το μπάνιο. Follow the marked edge.');
  await expect(page.locator('.print-photos img')).toHaveCount(1);
  expect(await page.locator('.print-photos img').evaluateAll(images => images.every(image => (image as HTMLImageElement).naturalWidth > 0))).toBe(true);
});

test('failed location upload keeps its selection and requires a successful refresh before retry', async ({ page }) => {
  await login(page);
  const { projectId, recordId } = seed();
  const base = `/api/projects/${projectId}/records/${recordId}`;
  await page.goto(`/projects/${projectId}/records/${recordId}`);
  await page.getByRole('button', { name: 'Edit record', exact: true }).click();
  await page.getByRole('textbox', { name: 'Location Notes', exact: true }).fill('Keep this text after upload failure');
  const photos = page.getByRole('region', { name: 'Location photos', exact: true });
  await photos.getByLabel('Files', { exact: true }).setInputFiles(resolve('tests/browser/fixtures/media-oriented.jpg'));
  await page.route('**' + base + '/photos', route => route.request().method() === 'POST' ? route.abort() : route.fulfill({ status: 503, json: { error: 'unavailable' } }));
  await photos.getByRole('button', { name: 'Upload location photos', exact: true }).click();
  await expect(photos.getByRole('alert')).toBeVisible();
  const upload = photos.getByRole('button', { name: 'Upload location photos', exact: true });
  await expect(upload).toBeDisabled();
  await photos.getByRole('button', { name: 'Refresh evidence before retrying', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Loading record' })).toHaveCount(0);
  await expect(upload).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Location Notes', exact: true })).toHaveValue('Keep this text after upload failure');
  await expect(page.getByRole('button', { name: 'Save record', exact: true })).toBeDisabled();
  await page.unroute('**' + base + '/photos');
  await photos.getByRole('button', { name: 'Refresh evidence before retrying', exact: true }).click();
  await expect(upload).toBeEnabled();
  await photos.getByRole('button', { name: 'Clear selection', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Save record', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(page.getByText('Keep this text after upload failure', { exact: true })).toBeVisible();
});
