import { test, expect, login, seed } from './fixture';
const origin='http://127.0.0.1:3490';
test('child panels save independently without replacing an unsaved record draft',async({page})=>{
 await login(page);const {projectId}=seed();const base=`/api/projects/${projectId}/records`;
 const r=await(await page.request.post(base,{headers:{origin},data:{subtype:'task',title:'Retained draft'}})).json();
 await page.goto(`/projects/${projectId}/records/${r.id}`);await page.getByRole('button',{name:'Edit record',exact:true}).click();
 await page.getByLabel('Title',{exact:true}).fill('Not saved');await page.getByRole('button',{name:'Open Log',exact:true}).click();
 await page.getByRole('button',{name:'Add Log entry',exact:true}).click();await page.getByLabel('Entry',{exact:true}).fill('Independently saved');await page.getByRole('button',{name:'Save entry',exact:true}).click();
 await expect(page.getByRole('dialog').getByText('Independently saved',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();
 await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Not saved');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Cancel',exact:true}).click();
 expect((await(await page.request.get(`${base}/${r.id}`)).json()).title).toBe('Retained draft');expect((await(await page.request.get(`${base}/${r.id}/log`)).json())[0].text).toBe('Independently saved');
 await expect(page.getByRole('navigation',{name:'Record sections'}).getByRole('button')).toHaveCount(4);
});
test('record deletion names dependencies and requires the exact record ID',async({page})=>{
 await login(page);const {projectId}=seed();const base=`/api/projects/${projectId}/records`;
 const a=await(await page.request.post(base,{headers:{origin},data:{subtype:'task',title:'Disposable UI'}})).json();const b=await(await page.request.post(base,{headers:{origin},data:{subtype:'task',title:'Dependent UI',mustBeDoneBeforeIds:[a.id]}})).json();
 await page.goto(`/projects/${projectId}/records/${a.id}`);await page.getByRole('button',{name:'Delete record',exact:true}).click();await expect(page.getByRole('dialog')).toContainText(b.humanId);await expect(page.getByLabel('Type the record ID to confirm')).toHaveCount(0);await page.getByRole('button',{name:'Keep record',exact:true}).click();
 await page.request.patch(`${base}/${b.id}`,{headers:{origin},data:{mustBeDoneBeforeIds:[]}});await page.getByRole('button',{name:'Delete record',exact:true}).click();await page.getByLabel('Type the record ID to confirm').fill(a.humanId);await page.getByRole('dialog').getByRole('button',{name:'Delete record',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/projects/${projectId}/records$`));expect((await page.request.get(`${base}/${a.id}`)).status()).toBe(404);
});
import Database from 'better-sqlite3';
test('overview retains verification notes and both sequence directions with reader restrictions',async({page,browser})=>{
 await login(page);const {projectId,architectId,dbPath}=seed();const base=`/api/projects/${projectId}/records`;
 const make=async(title:string,status='open')=>{const r=await(await page.request.post(base,{headers:{origin},data:{subtype:'task',title,notes:'Owner private content'}})).json();if(status==='open')expect((await page.request.post(`${base}/${r.id}/transitions`,{headers:{origin},data:{to:'open'}})).ok()).toBe(true);return r;};
 const r=await make('History destination');const incoming=await make('Incoming prerequisite');const outgoing=await make('Outgoing successor');const draft=await make('Hidden draft prerequisite','draft');
 await page.request.patch(`${base}/${incoming.id}`,{headers:{origin},data:{mustBeDoneBeforeIds:[r.id]}});await page.request.patch(`${base}/${draft.id}`,{headers:{origin},data:{mustBeDoneBeforeIds:[r.id]}});await page.request.patch(`${base}/${r.id}`,{headers:{origin},data:{mustBeDoneBeforeIds:[outgoing.id]}});
 const db=new Database(dbPath);try{for(const [outcome,note] of [['failed','First check\nneeds correction'],['passed','Second check\naccepted']])db.prepare('INSERT INTO verifications(record_id,checked_by_id,date,method,outcome,note,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(r.id,architectId,'2026-10-06','visual',outcome,note,'2026-10-06',1);}finally{db.close();}
 await page.goto(`/projects/${projectId}/records/${r.id}`);await page.getByText('Verification history (2)',{exact:true}).click();await expect(page.getByText('First check\nneeds correction',{exact:true})).toBeVisible();await expect(page.getByText('Second check\naccepted',{exact:true})).toBeVisible();await page.getByText('Sequence and dates',{exact:true}).click();await expect(page.getByText(`${outgoing.humanId} Outgoing successor`,{exact:true})).toBeVisible();await expect(page.locator('dd').filter({hasText:'Hidden draft prerequisite'})).toBeVisible();
 const link=await(await page.request.post(`${base}/${r.id}/share-links`,{headers:{origin},data:{label:'History reader'}})).json();const context=await browser.newContext();const reader=await context.newPage();try{await reader.goto(link.url);await reader.getByRole('combobox').selectOption('en');await reader.getByText('Verification history (2)',{exact:true}).click();await expect(reader.getByText('Second check\naccepted',{exact:true})).toBeVisible();await reader.getByText('Sequence and dates',{exact:true}).click();await expect(reader.getByText(`${incoming.humanId} Incoming prerequisite`,{exact:true})).toBeVisible();await expect(reader.locator('body')).not.toContainText('Hidden draft prerequisite');await expect(reader.locator('body')).not.toContainText('Owner private content');await expect(reader.getByRole('button',{name:'Delete record',exact:true})).toHaveCount(0);}finally{await context.close();}
});
test('phone actions return focus and owner editor survives transient refresh but clears on access loss',async({page})=>{
 await login(page);const {projectId}=seed();const r=await(await page.request.post(`/api/projects/${projectId}/records`,{headers:{origin},data:{subtype:'task',title:'Phone focus'}})).json();const base=`/api/projects/${projectId}/records/${r.id}`;
 await page.setViewportSize({width:360,height:800});await page.goto(`/projects/${projectId}/records/${r.id}`);await page.getByRole('button',{name:'More',exact:true}).click();await page.getByRole('button',{name:'Activity history',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'More',exact:true})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Edit record',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Still here');await page.getByRole('button',{name:'Open Log',exact:true}).click();await page.getByRole('button',{name:'Add Log entry',exact:true}).click();await page.getByLabel('Entry',{exact:true}).fill('Saved despite refresh failure');await page.route(`**${base}`,route=>route.fulfill({status:503,json:{error:'temporary'}}));await page.getByRole('button',{name:'Save entry',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Still here');await page.unroute(`**${base}`);
 await page.getByRole('button',{name:'Open Log',exact:true}).click();await page.getByRole('button',{name:'Add Log entry',exact:true}).click();await page.getByLabel('Entry',{exact:true}).fill('Denied');await page.route(`**${base}/log`,route=>route.fulfill({status:403,json:{error:'forbidden'}}));await page.getByRole('button',{name:'Save entry',exact:true}).click();await expect(page.getByLabel('Title',{exact:true})).toHaveCount(0);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('body')).not.toContainText('Still here');
});
test('measurements save from the editor and required-field correction retains the chosen transition',async({page})=>{
 await login(page);const {projectId}=seed();const base=`/api/projects/${projectId}/records`;const r=await(await page.request.post(base,{headers:{origin},data:{subtype:'task'}})).json();await page.goto(`/projects/${projectId}/records/${r.id}`);await page.getByRole('button',{name:'Change status',exact:true}).click();await page.getByLabel('New status',{exact:true}).selectOption('open');await page.getByLabel('Transition note',{exact:true}).fill('Keep transition wording');await page.getByRole('button',{name:'Apply status',exact:true}).click();await page.getByRole('button',{name:'Edit required fields',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Corrected title');await page.getByRole('button',{name:'Open Measurements',exact:true}).click();await page.getByRole('button',{name:'Add measurement set',exact:true}).click();await page.getByLabel('Item',{exact:true}).fill('Frame');await page.getByLabel('Quantity',{exact:true}).fill('Offset');await page.getByLabel('Value',{exact:true}).fill('0.4');await page.getByRole('button',{name:'Save measurements',exact:true}).click();await page.getByRole('button',{name:'Close',exact:true}).click();await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Corrected title');await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByLabel('New status',{exact:true})).toHaveValue('open');await expect(page.getByLabel('Transition note',{exact:true})).toHaveValue('Keep transition wording');await page.getByRole('button',{name:'Apply status',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect((await(await page.request.get(`${base}/${r.id}/measurement-sets`)).json())[0].rows[0].value).toBe(.4);
});
test('entering record editing protects pending location-photo selections and captions',async({page})=>{
 await login(page);const {projectId}=seed();const r=await(await page.request.post(`/api/projects/${projectId}/records`,{headers:{origin},data:{subtype:'task',title:'Pending location'}})).json();await page.goto(`/projects/${projectId}/records/${r.id}`);const photos=page.getByRole('region',{name:'Location photos',exact:true});await photos.getByLabel('Files',{exact:true}).setInputFiles({name:'pending.png',mimeType:'image/png',buffer:Buffer.from('pending selection, not uploaded')});await photos.getByLabel('Caption',{exact:true}).fill('Keep this caption');let prompted=false;page.once('dialog',async dialog=>{prompted=true;await dialog.dismiss();});await page.getByRole('button',{name:'Edit record',exact:true}).click();expect(prompted).toBe(true);await expect(photos.getByLabel('Caption',{exact:true})).toHaveValue('Keep this caption');await expect(photos.getByText('pending.png',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Save record',exact:true})).toHaveCount(0);
});
test('opening and closing status or Sharing cannot clear an underlying evidence draft',async({page})=>{
 await login(page);const {projectId}=seed();const r=await(await page.request.post(`/api/projects/${projectId}/records`,{headers:{origin},data:{subtype:'task',title:'Protected upload'}})).json();await page.goto(`/projects/${projectId}/records/${r.id}`);await page.getByRole('button',{name:'Photos & files',exact:true}).click();await page.getByLabel('Caption',{exact:true}).fill('Pending evidence caption');await page.getByLabel('Files',{exact:true}).setInputFiles({name:'pending.png',mimeType:'image/png',buffer:Buffer.from('not sent')});
 for(const action of ['Change status','Sharing']){await page.getByRole('button',{name:action,exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:action==='Sharing'?'Close':'Cancel',exact:true}).click();let prompted=false;page.once('dialog',async d=>{prompted=true;await d.dismiss();});await page.getByRole('button',{name:'Overview',exact:true}).click();expect(prompted).toBe(true);await expect(page.getByLabel('Caption',{exact:true})).toHaveValue('Pending evidence caption');await expect(page.getByText('pending.png',{exact:true})).toBeVisible();}
});
test('active evidence upload disables record editing until its result is known',async({page})=>{
 await login(page);const {projectId}=seed();const r=await(await page.request.post(`/api/projects/${projectId}/records`,{headers:{origin},data:{subtype:'task',title:'Upload guard'}})).json();const base=`/api/projects/${projectId}/records/${r.id}`;await page.goto(`/projects/${projectId}/records/${r.id}`);await page.getByRole('button',{name:'Photos & files',exact:true}).click();await page.getByLabel('Upload type',{exact:true}).selectOption('attachments');await page.getByLabel('Files',{exact:true}).setInputFiles({name:'pending.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic pending upload')});let release!:()=>void;let started!:()=>void;const ready=new Promise<void>(r=>{started=r;});const gate=new Promise<void>(r=>{release=r;});await page.route(`**${base}/attachments`,async route=>{if(route.request().method()==='POST'){started();await gate;}await route.continue();});await page.getByRole('button',{name:'Upload evidence',exact:true}).click();await ready;await expect(page.getByRole('button',{name:'Edit record',exact:true})).toBeDisabled();release();await expect(page.getByText('Upload complete.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Edit record',exact:true})).toBeEnabled();
});
