// GENERATED by scripts/extract-vocabulary.mjs from docs/designs/2026-10-02-v1-records-design.md §7. Do not edit by hand.
// Regenerate with: npm run vocabulary:extract

export const VOCABULARY = {
  "subtype": [
    {
      "code": "quality_issue",
      "en": "Quality Issue",
      "el": "Ζήτημα ποιότητας",
      "defEn": "Something wrong with work that has already been built.",
      "defEl": "Πρόβλημα σε εργασία που έχει ήδη εκτελεστεί."
    },
    {
      "code": "detail_clarification",
      "en": "Detail Clarification",
      "el": "Τεχνική διευκρίνιση",
      "defEn": "An instruction or detail agreed before something is built, to prevent problems.",
      "defEl": "Οδηγία ή λεπτομέρεια που συμφωνείται πριν από την κατασκευή, ώστε να προληφθούν προβλήματα."
    },
    {
      "code": "task",
      "en": "Task",
      "el": "Εργασία",
      "defEn": "Any other piece of work to track.",
      "defEl": "Οποιαδήποτε άλλη εργασία προς παρακολούθηση."
    }
  ],
  "status": [
    {
      "code": "draft",
      "en": "Draft",
      "el": "Πρόχειρο",
      "defEn": "Not finished being written. Never shown in share links.",
      "defEl": "Η καταχώριση δεν έχει ολοκληρωθεί. Δεν εμφανίζεται ποτέ σε συνδέσμους κοινοποίησης."
    },
    {
      "code": "open",
      "en": "Open",
      "el": "Ανοιχτό",
      "defEn": "Logged and complete, but nobody has yet been asked to decide or act.",
      "defEl": "Καταγράφηκε πλήρως, αλλά δεν έχει ζητηθεί ακόμη από κανέναν να αποφασίσει ή να ενεργήσει."
    },
    {
      "code": "awaiting_decision",
      "en": "Awaiting decision",
      "el": "Αναμονή απόφασης",
      "defEn": "Someone (usually the architect) has been asked to decide what should be done.",
      "defEl": "Έχει ζητηθεί από κάποιον (συνήθως τον αρχιτέκτονα) να αποφασίσει τι πρέπει να γίνει."
    },
    {
      "code": "issued",
      "en": "Issued",
      "el": "Εκδόθηκε",
      "defEn": "The decision is made and the instruction has gone to whoever does the work; the work has not started.",
      "defEl": "Η απόφαση πάρθηκε και η εντολή δόθηκε σε όποιον εκτελεί την εργασία· η εργασία δεν έχει ξεκινήσει."
    },
    {
      "code": "in_progress",
      "en": "In progress",
      "el": "Σε εξέλιξη",
      "defEn": "The work has started.",
      "defEl": "Η εργασία έχει ξεκινήσει."
    },
    {
      "code": "ready_for_verification",
      "en": "Ready for verification",
      "el": "Προς έλεγχο",
      "defEn": "Reported as done; waiting for someone to check it.",
      "defEl": "Δηλώθηκε ως ολοκληρωμένο· αναμένεται έλεγχος."
    },
    {
      "code": "on_hold",
      "en": "On hold",
      "el": "Σε αναμονή",
      "defEn": "Paused by a decision or by circumstances. A reason is required.",
      "defEl": "Σε παύση λόγω απόφασης ή συνθηκών. Απαιτείται αιτιολογία."
    },
    {
      "code": "closed",
      "en": "Closed",
      "el": "Κλειστό",
      "defEn": "Finished; nothing more to do.",
      "defEl": "Ολοκληρώθηκε· δεν απαιτείται άλλη ενέργεια."
    },
    {
      "code": "cancelled",
      "en": "Cancelled",
      "el": "Ακυρώθηκε",
      "defEn": "Will not be pursued. A reason is required.",
      "defEl": "Δεν θα προχωρήσει. Απαιτείται αιτιολογία."
    },
    {
      "code": "superseded",
      "en": "Superseded",
      "el": "Αντικαταστάθηκε",
      "defEn": "Replaced by a later clarification and kept as history. Detail Clarification only.",
      "defEl": "Αντικαταστάθηκε από μεταγενέστερη διευκρίνιση και διατηρείται ως ιστορικό. Μόνο για τεχνικές διευκρινίσεις."
    }
  ],
  "onHoldReason": [
    {
      "code": "waiting_material",
      "en": "Waiting for material",
      "el": "Αναμονή υλικού",
      "defEn": "Needed material or equipment has not arrived.",
      "defEl": "Δεν έχει φτάσει το απαιτούμενο υλικό ή εξοπλισμός."
    },
    {
      "code": "waiting_trade",
      "en": "Waiting for another trade",
      "el": "Αναμονή άλλης ειδικότητας",
      "defEn": "Another trade must work first.",
      "defEl": "Πρέπει πρώτα να εργαστεί άλλη ειδικότητα."
    },
    {
      "code": "waiting_information",
      "en": "Waiting for information",
      "el": "Αναμονή πληροφοριών",
      "defEn": "Information or documents are missing.",
      "defEl": "Λείπουν πληροφορίες ή έγγραφα."
    },
    {
      "code": "deferred",
      "en": "Deferred",
      "el": "Αναβολή",
      "defEn": "Deliberately postponed, e.g. to winter or a later stage.",
      "defEl": "Μετατέθηκε σκόπιμα, π.χ. για τον χειμώνα ή για επόμενο στάδιο."
    },
    {
      "code": "weather",
      "en": "Weather",
      "el": "Καιρικές συνθήκες",
      "defEn": "The weather prevents the work.",
      "defEl": "Οι καιρικές συνθήκες δεν επιτρέπουν την εργασία."
    },
    {
      "code": "other",
      "en": "Other",
      "el": "Άλλο",
      "defEn": "Any other reason, explained in the note.",
      "defEl": "Άλλος λόγος, που εξηγείται στη σημείωση."
    }
  ],
  "cancellationReason": [
    {
      "code": "duplicate",
      "en": "Duplicate",
      "el": "Διπλοεγγραφή",
      "defEn": "The same matter is already recorded.",
      "defEl": "Το ίδιο θέμα έχει ήδη καταχωριστεί."
    },
    {
      "code": "raised_in_error",
      "en": "Raised in error",
      "el": "Λάθος καταχώριση",
      "defEn": "Recorded by mistake.",
      "defEl": "Καταχωρίστηκε κατά λάθος."
    },
    {
      "code": "no_longer_needed",
      "en": "No longer needed",
      "el": "Δεν χρειάζεται πλέον",
      "defEn": "Circumstances changed; nothing needs doing.",
      "defEl": "Οι συνθήκες άλλαξαν· δεν απαιτείται ενέργεια."
    },
    {
      "code": "replaced",
      "en": "Replaced by another record",
      "el": "Αντικαταστάθηκε από άλλη εγγραφή",
      "defEn": "Continued in another record, whose ID is written in the note.",
      "defEl": "Συνεχίζεται σε άλλη εγγραφή, ο κωδικός της οποίας σημειώνεται στη σημείωση."
    },
    {
      "code": "other",
      "en": "Other",
      "el": "Άλλο",
      "defEn": "Any other reason, explained in the note.",
      "defEl": "Άλλος λόγος, που εξηγείται στη σημείωση."
    }
  ],
  "problemType": [
    {
      "code": "nonconformance",
      "en": "Nonconformance",
      "el": "Μη συμμόρφωση",
      "defEn": "Differs from an agreed requirement (drawing, specification, instruction or clarification). Write the requirement in Reference.",
      "defEl": "Διαφέρει από συμφωνημένη απαίτηση (σχέδιο, προδιαγραφή, εντολή ή διευκρίνιση). Η απαίτηση σημειώνεται στο πεδίο Αναφορά."
    },
    {
      "code": "defect",
      "en": "Defect",
      "el": "Ελάττωμα",
      "defEn": "Faulty workmanship or material.",
      "defEl": "Κακοτεχνία ή ελαττωματικό υλικό."
    },
    {
      "code": "incomplete",
      "en": "Incomplete work",
      "el": "Ημιτελής εργασία",
      "defEn": "Work that has not been finished.",
      "defEl": "Εργασία που δεν έχει ολοκληρωθεί."
    },
    {
      "code": "damage",
      "en": "Damage",
      "el": "Φθορά / Ζημιά",
      "defEn": "Was fine, damaged afterwards.",
      "defEl": "Ήταν σε καλή κατάσταση και υπέστη ζημιά αργότερα."
    },
    {
      "code": "design_coordination",
      "en": "Design / coordination issue",
      "el": "Σφάλμα μελέτης / συντονισμού",
      "defEn": "Built as drawn, but the design is wrong, incomplete, or clashes with other work.",
      "defEl": "Κατασκευάστηκε σύμφωνα με τα σχέδια, αλλά η μελέτη είναι λανθασμένη, ελλιπής ή συγκρούεται με άλλες εργασίες."
    },
    {
      "code": "other",
      "en": "Other",
      "el": "Άλλο",
      "defEn": "None of the above.",
      "defEl": "Κανένα από τα παραπάνω."
    }
  ],
  "stage": [
    {
      "code": "construction",
      "en": "Construction",
      "el": "Κατασκευή",
      "defEn": "Found while the works are still ongoing.",
      "defEl": "Εντοπίστηκε ενώ οι εργασίες βρίσκονται σε εξέλιξη."
    },
    {
      "code": "pre_handover",
      "en": "Pre-handover",
      "el": "Προ-παράδοση",
      "defEn": "Found in the owner's own checks before the formal handover inspection (\"pre-punch\").",
      "defEl": "Εντοπίστηκε σε ελέγχους του ιδιοκτήτη πριν από την επίσημη αυτοψία παράδοσης."
    },
    {
      "code": "handover",
      "en": "Handover",
      "el": "Παράδοση",
      "defEn": "Found at the formal handover inspection (punch / snag list).",
      "defEl": "Εντοπίστηκε στην επίσημη αυτοψία παράδοσης (λίστα παρατηρήσεων)."
    },
    {
      "code": "warranty",
      "en": "Warranty",
      "el": "Περίοδος εγγύησης",
      "defEn": "Found after handover, during the defects liability period.",
      "defEl": "Εντοπίστηκε μετά την παράδοση, εντός της περιόδου εγγύησης."
    }
  ],
  "disposition": [
    {
      "code": "rework",
      "en": "Rework",
      "el": "Επανεκτέλεση",
      "defEn": "Modify the existing work until it matches what was agreed.",
      "defEl": "Τροποποίηση της υφιστάμενης εργασίας ώστε να συμφωνεί με τα συμφωνημένα."
    },
    {
      "code": "replace",
      "en": "Replace",
      "el": "Αντικατάσταση",
      "defEn": "Remove and build again.",
      "defEl": "Αφαίρεση και εκ νέου κατασκευή."
    },
    {
      "code": "repair",
      "en": "Repair",
      "el": "Επισκευή",
      "defEn": "Make it acceptable without fully matching what was agreed. Requires approval from the authorised decision-maker, recorded in Decided by / Decided on.",
      "defEl": "Αποκατάσταση σε αποδεκτό επίπεδο χωρίς πλήρη συμφωνία με τα συμφωνημένα. Απαιτεί έγκριση από τον αρμόδιο, με καταγραφή του ονόματος και της ημερομηνίας απόφασης."
    },
    {
      "code": "accept_as_is",
      "en": "Accept as is",
      "el": "Αποδοχή ως έχει",
      "defEn": "Leave it; the deviation is accepted by whoever has the authority.",
      "defEl": "Παραμένει ως έχει· η απόκλιση γίνεται αποδεκτή από τον αρμόδιο."
    }
  ],
  "route": [
    {
      "code": "rfi",
      "en": "RFI",
      "el": "Αίτημα διευκρίνισης",
      "defEn": "The contractor asks the designer to clarify something before building.",
      "defEl": "Ο εργολάβος ζητά από τον μελετητή διευκρίνιση πριν από την κατασκευή."
    },
    {
      "code": "instruction",
      "en": "Instruction",
      "el": "Εντολή",
      "defEn": "A detail or instruction is issued, on the issuer's own initiative or after discussion.",
      "defEl": "Εκδίδεται λεπτομέρεια ή εντολή, με πρωτοβουλία του εκδότη ή μετά από συζήτηση."
    },
    {
      "code": "submittal",
      "en": "Submittal",
      "el": "Υποβολή προς έγκριση",
      "defEn": "The contractor submits a drawing, product or sample for approval before using it.",
      "defEl": "Ο εργολάβος υποβάλλει σχέδιο, προϊόν ή δείγμα προς έγκριση πριν από τη χρήση του."
    },
    {
      "code": "mockup",
      "en": "Mock-up",
      "el": "Δείγμα / δοκιμαστική κατασκευή",
      "defEn": "One is built first and approved, then repeated.",
      "defEl": "Κατασκευάζεται πρώτα ένα δείγμα, εγκρίνεται και έπειτα επαναλαμβάνεται."
    },
    {
      "code": "other",
      "en": "Other",
      "el": "Άλλο",
      "defEn": "Any other route.",
      "defEl": "Άλλη διαδικασία."
    }
  ],
  "severity": [
    {
      "code": "critical",
      "en": "Critical",
      "el": "Κρίσιμο",
      "defEn": "Serious safety risk, structural failure or major water ingress.",
      "defEl": "Σοβαρός κίνδυνος για την ασφάλεια, αστοχία του φέροντος οργανισμού ή εκτεταμένη εισροή νερού."
    },
    {
      "code": "major",
      "en": "Major",
      "el": "Σημαντικό",
      "defEn": "Material impairment of function, durability or appearance.",
      "defEl": "Ουσιώδης υποβάθμιση της λειτουργίας, της ανθεκτικότητας ή της εμφάνισης."
    },
    {
      "code": "minor",
      "en": "Minor",
      "el": "Μικρό",
      "defEn": "Local cosmetic imperfection, with no material effect on function or safety.",
      "defEl": "Τοπική αισθητική ατέλεια, χωρίς ουσιώδεις επιπτώσεις στη λειτουργία ή την ασφάλεια."
    }
  ],
  "priority": [
    {
      "code": "urgent",
      "en": "Urgent",
      "el": "Επείγον",
      "defEn": "Act now: something is waiting on it today or this week.",
      "defEl": "Άμεση ενέργεια: κάτι εξαρτάται από αυτό σήμερα ή αυτή την εβδομάδα."
    },
    {
      "code": "high",
      "en": "High",
      "el": "Υψηλή",
      "defEn": "Deal with it in the current work cycle (the next one to two weeks).",
      "defEl": "Αντιμετώπιση στον τρέχοντα κύκλο εργασιών (τις επόμενες μία έως δύο εβδομάδες)."
    },
    {
      "code": "medium",
      "en": "Medium",
      "el": "Μεσαία",
      "defEn": "Schedule normally, before the current stage ends.",
      "defEl": "Κανονικός προγραμματισμός, πριν ολοκληρωθεί το τρέχον στάδιο."
    },
    {
      "code": "low",
      "en": "Low",
      "el": "Χαμηλή",
      "defEn": "No time pressure; whenever convenient.",
      "defEl": "Χωρίς χρονική πίεση· όποτε είναι βολικό."
    }
  ],
  "personRole": [
    {
      "code": "owner",
      "en": "Owner",
      "el": "Ιδιοκτήτης",
      "defEn": "The project owner.",
      "defEl": "Ο ιδιοκτήτης του έργου."
    },
    {
      "code": "owner_rep",
      "en": "Owner's representative",
      "el": "Εκπρόσωπος ιδιοκτήτη",
      "defEn": "Acts on site or in decisions on the owner's behalf.",
      "defEl": "Ενεργεί στο έργο ή στις αποφάσεις για λογαριασμό του ιδιοκτήτη."
    },
    {
      "code": "architect",
      "en": "Architect / designer",
      "el": "Αρχιτέκτονας / μελετητής",
      "defEn": "Designs the work and decides design questions.",
      "defEl": "Μελετά το έργο και αποφασίζει για θέματα μελέτης."
    },
    {
      "code": "engineer",
      "en": "Engineer",
      "el": "Μηχανικός",
      "defEn": "Structural, mechanical or electrical engineer.",
      "defEl": "Στατικός, μηχανολόγος ή ηλεκτρολόγος μηχανικός."
    },
    {
      "code": "main_contractor",
      "en": "Main contractor",
      "el": "Γενικός εργολάβος",
      "defEn": "Holds the main construction contract.",
      "defEl": "Έχει την κύρια σύμβαση κατασκευής."
    },
    {
      "code": "subcontractor",
      "en": "Subcontractor",
      "el": "Υπεργολάβος",
      "defEn": "Carries out a specific trade or package.",
      "defEl": "Εκτελεί συγκεκριμένη ειδικότητα ή πακέτο εργασιών."
    },
    {
      "code": "supplier",
      "en": "Supplier",
      "el": "Προμηθευτής",
      "defEn": "Supplies materials or equipment.",
      "defEl": "Προμηθεύει υλικά ή εξοπλισμό."
    },
    {
      "code": "other",
      "en": "Other",
      "el": "Άλλος",
      "defEn": "Anyone else.",
      "defEl": "Οποιοσδήποτε άλλος."
    }
  ],
  "locationNodeKind": [
    {
      "code": "building",
      "en": "Building",
      "el": "Κτίριο",
      "defEn": "A building, or a group of works treated as one (e.g. \"Site — shared infrastructure\", \"Off-site\").",
      "defEl": "Κτίριο ή ομάδα εργασιών που αντιμετωπίζεται ενιαία (π.χ. «Κοινόχρηστες υποδομές», «Εκτός έργου»)."
    },
    {
      "code": "level",
      "en": "Level",
      "el": "Επίπεδο",
      "defEn": "A floor or level (basement, ground, upper, roof, external).",
      "defEl": "Όροφος ή επίπεδο (υπόγειο, ισόγειο, όροφος, δώμα, εξωτερικός χώρος)."
    },
    {
      "code": "space",
      "en": "Space",
      "el": "Χώρος",
      "defEn": "A room or defined area within a level.",
      "defEl": "Δωμάτιο ή οριοθετημένος χώρος μέσα σε επίπεδο."
    },
    {
      "code": "other",
      "en": "Other",
      "el": "Άλλο",
      "defEn": "Any other kind of place.",
      "defEl": "Άλλο είδος θέσης."
    }
  ],
  "measurementPhase": [
    {
      "code": "before",
      "en": "Before",
      "el": "Πριν",
      "defEn": "Measured before the correction or work.",
      "defEl": "Μέτρηση πριν από τη διόρθωση ή την εργασία."
    },
    {
      "code": "after",
      "en": "After",
      "el": "Μετά",
      "defEn": "Measured after the correction or work.",
      "defEl": "Μέτρηση μετά τη διόρθωση ή την εργασία."
    },
    {
      "code": "other",
      "en": "Other",
      "el": "Άλλο",
      "defEn": "Any other moment, e.g. an interim check.",
      "defEl": "Άλλη χρονική στιγμή, π.χ. ενδιάμεσος έλεγχος."
    }
  ],
  "unit": [
    {
      "code": "mm",
      "en": "mm",
      "el": "χιλ.",
      "defEn": "Millimetre.",
      "defEl": "Χιλιοστό του μέτρου."
    },
    {
      "code": "cm",
      "en": "cm",
      "el": "εκ.",
      "defEn": "Centimetre.",
      "defEl": "Εκατοστό του μέτρου."
    },
    {
      "code": "m",
      "en": "m",
      "el": "μ.",
      "defEn": "Metre.",
      "defEl": "Μέτρο."
    },
    {
      "code": "m2",
      "en": "m²",
      "el": "τ.μ.",
      "defEn": "Square metre.",
      "defEl": "Τετραγωνικό μέτρο."
    },
    {
      "code": "m3",
      "en": "m³",
      "el": "κ.μ.",
      "defEn": "Cubic metre.",
      "defEl": "Κυβικό μέτρο."
    },
    {
      "code": "percent",
      "en": "%",
      "el": "%",
      "defEn": "Percentage, e.g. a slope.",
      "defEl": "Ποσοστό, π.χ. κλίση."
    },
    {
      "code": "degree",
      "en": "°",
      "el": "°",
      "defEn": "Angle in degrees.",
      "defEl": "Γωνία σε μοίρες."
    },
    {
      "code": "pcs",
      "en": "pcs",
      "el": "τεμ.",
      "defEn": "Number of pieces.",
      "defEl": "Αριθμός τεμαχίων."
    }
  ],
  "photoPhase": [
    {
      "code": "before",
      "en": "Before",
      "el": "Πριν",
      "defEn": "Shows the condition before the correction or work.",
      "defEl": "Δείχνει την κατάσταση πριν από τη διόρθωση ή την εργασία."
    },
    {
      "code": "during",
      "en": "During",
      "el": "Κατά τη διάρκεια",
      "defEn": "Taken while the work is underway.",
      "defEl": "Λήφθηκε κατά την εκτέλεση της εργασίας."
    },
    {
      "code": "after",
      "en": "After",
      "el": "Μετά",
      "defEn": "Shows the finished result.",
      "defEl": "Δείχνει το τελικό αποτέλεσμα."
    }
  ],
  "verificationMethod": [
    {
      "code": "visual",
      "en": "Visual",
      "el": "Οπτικός",
      "defEn": "Checked by looking at the work, on site or in photos.",
      "defEl": "Έλεγχος με επιθεώρηση της εργασίας, επί τόπου ή μέσω φωτογραφιών."
    },
    {
      "code": "measurement",
      "en": "Measurement",
      "el": "Μέτρηση",
      "defEn": "Checked with a recorded measurement set.",
      "defEl": "Έλεγχος με καταγεγραμμένες μετρήσεις."
    },
    {
      "code": "document",
      "en": "Document",
      "el": "Έγγραφο",
      "defEn": "Checked against a certificate, declaration or report.",
      "defEl": "Έλεγχος μέσω πιστοποιητικού, δήλωσης ή έκθεσης."
    },
    {
      "code": "test",
      "en": "Test",
      "el": "Δοκιμή",
      "defEn": "Checked by a functional test (e.g. water, pressure, electrical).",
      "defEl": "Έλεγχος με δοκιμή λειτουργίας (π.χ. στεγανότητας, πίεσης, ηλεκτρολογική)."
    }
  ],
  "verificationOutcome": [
    {
      "code": "passed",
      "en": "Passed",
      "el": "Επιτυχής",
      "defEn": "The check confirmed the result is acceptable.",
      "defEl": "Ο έλεγχος επιβεβαίωσε ότι το αποτέλεσμα είναι αποδεκτό."
    },
    {
      "code": "failed",
      "en": "Failed",
      "el": "Ανεπιτυχής",
      "defEn": "The check found that further work is required.",
      "defEl": "Ο έλεγχος έδειξε ότι απαιτούνται πρόσθετες εργασίες."
    }
  ]
} as const satisfies Record<
  string,
  readonly { code: string; en: string; el: string; defEn: string; defEl: string }[]
>;
