import { useEffect, useRef, useState } from 'react';
import type { RecordDetail } from '../../server/records/records';
import { api, ApiError } from '../core/api';
import { ErrorNotice, Field } from '../core/forms';
import { useI18n } from '../core/i18n';
export function DeleteRecordDialog({base,onClose,onDeleted}:{base:string;onClose:()=>void;onDeleted:()=>void}){
 const {t}=useI18n();const dialog=useRef<HTMLDialogElement>(null);const [record,setRecord]=useState<RecordDetail|null>(null);const [references,setReferences]=useState<{id:number;humanId:string;title:string|null}[]>([]);const [confirmation,setConfirmation]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);
 useEffect(()=>{const opener=document.activeElement as HTMLElement;dialog.current?.showModal();const controller=new AbortController();api<RecordDetail>(base,{signal:controller.signal}).then(r=>{setRecord(r);setReferences([...r.mustBeDoneBefore,...r.requiresFirst]);}).catch(e=>{if(!controller.signal.aborted)setError(e);});return()=>{controller.abort();opener?.focus();};},[base]);
 async function remove(){if(!record||busy||confirmation!==record.humanId)return;setBusy(true);setError(null);try{await api(base,{method:'DELETE',body:{confirmHumanId:confirmation}});onDeleted();}catch(e){if(e instanceof ApiError&&e.code==='record_has_dependencies')setReferences((e.details as {records:typeof references}).records);setError(e);}finally{setBusy(false);}}
 return <dialog ref={dialog} className="dialog" aria-label={t('Delete record?','Διαγραφή καταγραφής;')} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><h2>{t('Delete record?','Διαγραφή καταγραφής;')}</h2><ErrorNotice error={error}/>{record&&<><p><strong>{record.humanId} · {record.title}</strong></p>{references.length?<><p>{t('Remove these sequence relationships before deleting the record.','Αφαιρέστε αυτές τις σχέσεις σειράς εργασιών πριν διαγράψετε την καταγραφή.')}</p><ul>{references.map((r,i)=><li key={i}>{r.humanId} · {r.title}</li>)}</ul></>:<><p>{t('This permanently deletes the record, its photos and attachment entries, Log, measurements, history, grants and share links. Stored files are retained. Cancelled preserves the record and its history.','Διαγράφονται οριστικά η καταγραφή, οι καταχωρίσεις φωτογραφιών και συνημμένων, το ημερολόγιο, οι μετρήσεις, το ιστορικό, τα δικαιώματα και οι σύνδεσμοι κοινοποίησης. Τα αποθηκευμένα αρχεία διατηρούνται. Η κατάσταση Ακυρωμένη διατηρεί την καταγραφή και το ιστορικό της.')}</p><Field label={t('Type the record ID to confirm','Πληκτρολογήστε τον κωδικό καταγραφής για επιβεβαίωση')}><input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></Field><button className="destructive" disabled={busy||confirmation!==record.humanId} onClick={()=>void remove()}>{t('Delete record','Διαγραφή καταγραφής')}</button></>}</>}<button disabled={busy} onClick={onClose}>{t('Keep record','Διατήρηση καταγραφής')}</button></dialog>;
}
