import { IconButton } from '../core/IconButton';
import { useState } from 'react';
import { compareItems, compareOverTime, labelOf, normalizeLabel, orderSets, type MeasurementSetInput, type SharedRecord, type Unit, type MeasurementPhase } from '../../domain';
import { BusyButton, Field, PersonSelect, VocabSelect } from '../core/forms';
import { useI18n } from '../core/i18n';
import { dateText, localInput, measurementGroups, signedBar } from './helpers';
import { measurementNumber } from './number-format';

type Set = SharedRecord['measurements'][number];
function SignedBar({ value, max }: { value: number; max: number }) {
  const bar = signedBar(value, max);
  return <span aria-hidden="true" style={{ display: 'inline-block', position: 'relative', width: 120, height: 14, marginInlineEnd: 8 }}><span style={{ position: 'absolute', left: '50%', top: 0, height: 14, borderLeft: '1px solid currentColor' }} /><span style={{ position: 'absolute', left: `${bar.left}%`, width: `${bar.width}%`, top: 3, height: 8, background: 'currentColor' }} /></span>;
}
type DraftRow = { item: string; quantity: string; unit: Unit; value: string; note: string };
const emptyRow = (): DraftRow => ({ item: '', quantity: '', unit: 'mm', value: '', note: '' });
export function MeasurementEditor({ initial, sets, people, busy, onSave, onCancel, onDirty }: { initial?: Set; sets: Set[]; people: { id: number; name: string; active?: boolean }[]; busy: boolean; onSave: (body: MeasurementSetInput) => Promise<void>; onCancel: () => void; onDirty: () => void }) {
  const { t } = useI18n(); const [date, setDate] = useState(initial?.date ?? localInput().slice(0, 10)); const [phase, setPhase] = useState<MeasurementPhase>(initial?.phase ?? 'before'); const [person, setPerson] = useState(initial?.measuredById ?? null); const [note, setNote] = useState(initial?.note ?? '');
  const [rows, setRows] = useState<DraftRow[]>(initial?.rows.map(row => ({ ...row, value: String(row.value), note: row.note ?? '' })) ?? [emptyRow()]);
  const update = (index: number, patch: Partial<DraftRow>) => { setRows(old => old.map((row, i) => i === index ? { ...row, ...patch } : row)); onDirty(); };
  return <form onChange={onDirty} onSubmit={e => { e.preventDefault(); void onSave({ date, phase, measuredById: person, note, rows: rows.map(row => ({ ...row, value: Number(row.value) })) }); }}><fieldset disabled={busy}><legend>{t('Measurement set', 'Σύνολο μετρήσεων')}</legend>
    <Field label={t('Date', 'Ημερομηνία')}><input type="date" required value={date} onChange={e => setDate(e.target.value)} /></Field><VocabSelect list="measurementPhase" required label={t('Phase', 'Φάση')} value={phase} onChange={value => { setPhase(value as MeasurementPhase); onDirty(); }} /><PersonSelect label={t('Measured by', 'Μέτρησε')} people={people} value={person} onChange={value => { setPerson(value); onDirty(); }} /><Field label={t('Set note', 'Σημείωση συνόλου')}><textarea value={note} onChange={e => setNote(e.target.value)} /></Field>
    <datalist id="measurement-items">{[...new Set(sets.flatMap(set => set.rows.map(row => row.item)))].map(item => <option key={item} value={item} />)}</datalist><datalist id="measurement-quantities">{[...new Set(sets.flatMap(set => set.rows.map(row => row.quantity)))].map(item => <option key={item} value={item} />)}</datalist>
    {rows.map((row, index) => <fieldset key={index}><legend>{t('Row', 'Γραμμή')} {index + 1}</legend><div className="form-grid"><Field label={t('Item', 'Αντικείμενο')}><input required maxLength={200} list="measurement-items" value={row.item} onChange={e => update(index, { item: e.target.value })} /></Field><Field label={t('Quantity', 'Μέγεθος')}><input required maxLength={200} list="measurement-quantities" value={row.quantity} onChange={e => update(index, { quantity: e.target.value })} /></Field><Field label={t('Value', 'Τιμή')}><input type="number" step="any" required value={row.value} onChange={e => update(index, { value: e.target.value })} /></Field><VocabSelect list="unit" required label={t('Unit', 'Μονάδα')} value={row.unit} onChange={value => update(index, { unit: value as Unit })} /><Field label={t('Note', 'Σημείωση')}><input value={row.note} onChange={e => update(index, { note: e.target.value })} /></Field></div><button type="button" onClick={() => { setRows(old => old.filter((_, i) => index !== i)); onDirty(); }}>{t('Remove row', 'Αφαίρεση γραμμής')}</button></fieldset>)}
    <button type="button" onClick={() => { setRows(old => [...old, emptyRow()]); onDirty(); }}>{t('Add row', 'Προσθήκη γραμμής')}</button><BusyButton busy={busy} type="submit">{t('Save measurements', 'Αποθήκευση μετρήσεων')}</BusyButton><button type="button" onClick={onCancel}>{t('Cancel', 'Ακύρωση')}</button>
  </fieldset></form>;
}

export function Measurements({ sets, people, owner, onEdit, onDelete, onAdd }: { onAdd?:()=>void; sets: Set[]; people: { id: number; name: string }[]; owner: boolean; onEdit: (set: Set) => void; onDelete: (id: number) => void }) {
  const { t, lang } = useI18n(); const number = (value: number) => measurementNumber(value, lang);
  return <><div className="heading-actions"><h2>{t('Measurements','Μετρήσεις')}</h2>{owner && <IconButton icon="add" label={t('Add measurement set','Προσθήκη συνόλου μετρήσεων')} onClick={onAdd}/>}</div>{sets.length === 0 && <p>{t('No measurements yet.', 'Δεν υπάρχουν ακόμη μετρήσεις.')}</p>}
    {orderSets(sets).map(set => <article key={set.id}><h3>{dateText(set.date, lang)} · {labelOf('measurementPhase', set.phase, lang)}</h3><p>{people.find(person => person.id === set.measuredById)?.name}</p><p className="user-text">{set.note}</p><div className="table-scroll"><table><thead><tr>{[t('Item', 'Αντικείμενο'), t('Quantity', 'Μέγεθος'), t('Value', 'Τιμή'), t('Unit', 'Μονάδα'), t('Note', 'Σημείωση')].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{set.rows.map((row, i) => <tr key={i}><td>{row.item}</td><td>{row.quantity}</td><td>{number(row.value)}</td><td>{labelOf('unit', row.unit, lang)}</td><td className="user-text">{row.note}</td></tr>)}</tbody></table></div>
      {owner && <><IconButton icon="edit" label={t('Edit measurements','Επεξεργασία μετρήσεων')} onClick={()=>onEdit(set)}/><IconButton icon="delete" label={t('Delete measurement set','Διαγραφή συνόλου μετρήσεων')} onClick={()=>onDelete(set.id)}/></>}
      {[...new Map(set.rows.map(row => [JSON.stringify([normalizeLabel(row.quantity), row.unit]), row])).values()].map(row => { const comparisons = compareItems(set, row.quantity, row.unit); const max = Math.max(...comparisons.map(item => Math.abs(item.value)), 1); return <details key={`${row.quantity}-${row.unit}`}><summary>{t('Between items', 'Μεταξύ αντικειμένων')} · {row.quantity} ({labelOf('unit', row.unit, lang)})</summary><p>{t('Difference from the first item in display order.', 'Διαφορά από το πρώτο αντικείμενο στη σειρά εμφάνισης.')}</p><div className="table-scroll"><table><thead><tr><th>{t('Item', 'Αντικείμενο')}</th><th>{t('Value', 'Τιμή')}</th><th>{t('Difference', 'Διαφορά')}</th></tr></thead><tbody>{comparisons.map((item, i) => <tr key={i}><td>{item.item}</td><td><SignedBar value={item.value} max={max} />{number(item.value)}</td><td>{number(item.diffFromFirst)}</td></tr>)}</tbody></table></div></details>; })}
    </article>)}
    {measurementGroups(sets.flatMap(set => set.rows)).map(row => <details key={JSON.stringify([row.item, row.quantity, row.unit])}><summary>{t('Before vs after', 'Πριν και μετά')} · {row.item} · {row.quantity} ({labelOf('unit', row.unit, lang)})</summary><p>{t('Each change is the later value minus the previous value.', 'Κάθε μεταβολή είναι η νεότερη τιμή μείον την προηγούμενη.')}</p><div className="table-scroll"><table><thead><tr><th>{t('Date', 'Ημερομηνία')}</th><th>{t('Phase', 'Φάση')}</th><th>{t('Value', 'Τιμή')}</th><th>{t('Change', 'Μεταβολή')}</th></tr></thead><tbody>{compareOverTime(sets, row.item, row.quantity, row.unit).map(point => <tr key={point.setId}><td>{dateText(point.date, lang)}</td><td>{labelOf('measurementPhase', point.phase, lang)}</td><td>{number(point.value)}</td><td>{point.changeFromPrevious === null ? '—' : number(point.changeFromPrevious)}</td></tr>)}</tbody></table></div></details>)}
  </>;
}
