import { useEffect, useState } from 'react';
import type { ShareLinkOut } from '../../domain';
import { api } from '../core/api';
import { BusyButton, ErrorNotice, Field } from '../core/forms';
import { useI18n } from '../core/i18n';
import { dateText } from './helpers';

type Grant = { userId: number; canUpload: boolean; canAddLog: boolean };
type Contributor = { id: number; displayName: string; active: boolean };
export function Sharing({ base, draft, onAccessLost, onDirty }: { base: string; draft: boolean; onAccessLost: (error: unknown) => void; onDirty: (dirty: boolean) => void }) {
  const { t, lang } = useI18n(); const [links, setLinks] = useState<ShareLinkOut[]>([]); const [grants, setGrants] = useState<Grant[]>([]); const [people, setPeople] = useState<Contributor[]>([]); const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false); const [label, setLabel] = useState(''); const [expiry, setExpiry] = useState(''); const [selected, setSelected] = useState(''); const [upload, setUpload] = useState(false); const [log, setLog] = useState(false); const [copied, setCopied] = useState<number | null>(null);
  useEffect(() => { const controller = new AbortController(); void Promise.all([api<ShareLinkOut[]>(base + '/share-links', { signal: controller.signal }), api<Grant[]>(base + '/grants', { signal: controller.signal }), api<Contributor[]>('/api/contributors', { signal: controller.signal })]).then(([l, g, p]) => { setLinks(l); setGrants(g); setPeople(p); }).catch(reason => { if (!controller.signal.aborted) { setError(reason); onAccessLost(reason); } }); return () => controller.abort(); }, [base]);
  useEffect(() => { onDirty(Boolean(label || expiry || selected || upload || log || busy)); }, [label, expiry, selected, upload, log, busy, onDirty]);
  useEffect(() => () => onDirty(false), [onDirty]);
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(null); try { await action(); } catch (reason) { setError(reason); onAccessLost(reason); } finally { setBusy(false); } };
  return <section><h2>{t('Sharing and access', 'Κοινοποίηση και πρόσβαση')}</h2><ErrorNotice error={error} />{draft && <p>{t('Draft records are unavailable through links and contributor grants.', 'Οι πρόχειρες εγγραφές δεν είναι διαθέσιμες μέσω συνδέσμων και δικαιωμάτων συνεργατών.')}</p>}
    <h3>{t('Read-only links', 'Σύνδεσμοι μόνο για ανάγνωση')}</h3><p>{t('Anyone holding a link can read the public record until it expires or is revoked.', 'Όποιος έχει τον σύνδεσμο μπορεί να διαβάσει τη δημόσια εγγραφή μέχρι τη λήξη ή την ανάκλησή του.')}</p>
    {links.map(link => { const expired = !!link.expiresAt && Date.parse(link.expiresAt) <= Date.now(); return <article key={link.id}><h4>{link.label}</h4><dl><div><dt>{t('Created', 'Δημιουργία')}</dt><dd>{dateText(link.createdAt, lang)}</dd></div><div><dt>{t('Expires', 'Λήξη')}</dt><dd>{dateText(link.expiresAt, lang)}</dd></div><div><dt>{t('Last viewed', 'Τελευταία προβολή')}</dt><dd>{dateText(link.lastViewedAt, lang)}</dd></div><div><dt>{t('Views', 'Προβολές')}</dt><dd>{link.viewCount}</dd></div></dl><p>{link.revokedAt ? t('Revoked', 'Ανακλήθηκε') : expired ? t('Expired', 'Έληξε') : draft ? t('Draft — unavailable', 'Πρόχειρο — μη διαθέσιμο') : t('Active', 'Ενεργός')}</p>{link.url && <><Field label={t('Share URL', 'Διεύθυνση κοινοποίησης')}><input readOnly value={link.url} onFocus={e => e.target.select()} /></Field><button disabled={busy} onClick={() => void run(async () => { await navigator.clipboard.writeText(link.url!); setCopied(link.id); })}>{t('Copy link', 'Αντιγραφή συνδέσμου')}</button>{copied === link.id && <span role="status">{t('Copied', 'Αντιγράφηκε')}</span>}</>}{!link.revokedAt && <button disabled={busy} onClick={() => { if (window.confirm(t('Revoke this link? People using it will lose access.', 'Ανάκληση αυτού του συνδέσμου; Οι χρήστες του θα χάσουν την πρόσβαση.'))) void run(async () => { await api(base + `/share-links/${link.id}/revoke`, { method: 'POST', body: {} }); setLinks(await api(base + '/share-links')); }); }}>{t('Revoke link', 'Ανάκληση συνδέσμου')}</button>}</article>; })}
    <details><summary>{t('Create a share link', 'Δημιουργία συνδέσμου κοινοποίησης')}</summary><form onChange={() => onDirty(true)} onSubmit={e => { e.preventDefault(); void run(async () => { const link = await api<ShareLinkOut>(base + '/share-links', { method: 'POST', body: { label, expiresAt: expiry ? new Date(expiry).toISOString() : null } }); setLinks(old => [link, ...old]); setLabel(''); setExpiry(''); onDirty(false); }); }}><fieldset disabled={busy}><Field label={t('Link label', 'Τίτλος συνδέσμου')}><input required maxLength={200} value={label} onChange={e => setLabel(e.target.value)} /></Field><Field label={t('Expiry (optional)', 'Λήξη (προαιρετική)')}><input type="datetime-local" value={expiry} onChange={e => setExpiry(e.target.value)} /></Field><BusyButton busy={busy} type="submit">{t('Create link', 'Δημιουργία συνδέσμου')}</BusyButton></fieldset></form></details>
    <h3>{t('Named users', 'Ονομαστικοί χρήστες')}</h3><p>{t('Reading, uploading evidence and adding Log entries are separate permissions. Both switches off gives read-only access.', 'Η ανάγνωση, η μεταφόρτωση τεκμηρίων και η προσθήκη καταχωρίσεων είναι ανεξάρτητα δικαιώματα. Με τους δύο διακόπτες κλειστούς επιτρέπεται μόνο η ανάγνωση.')}</p>
    {grants.map(grant => <article key={grant.userId}><h4>{people.find(person => person.id === grant.userId)?.displayName ?? t('Unavailable user', 'Μη διαθέσιμος χρήστης')}</h4><p>{t('Upload evidence', 'Μεταφόρτωση τεκμηρίων')}: {grant.canUpload ? t('Yes', 'Ναι') : t('No', 'Όχι')} · {t('Add Log', 'Προσθήκη στο ημερολόγιο')}: {grant.canAddLog ? t('Yes', 'Ναι') : t('No', 'Όχι')}</p><button disabled={busy} onClick={() => { setSelected(String(grant.userId)); setUpload(grant.canUpload); setLog(grant.canAddLog); }}>{t('Edit access', 'Επεξεργασία πρόσβασης')}</button><button disabled={busy} onClick={() => { if (window.confirm(t('Remove this user’s access to the record?', 'Αφαίρεση πρόσβασης αυτού του χρήστη στην εγγραφή;'))) void run(async () => { await api(base + `/grants/${grant.userId}`, { method: 'DELETE' }); setGrants(old => old.filter(item => item.userId !== grant.userId)); }); }}>{t('Remove access', 'Αφαίρεση πρόσβασης')}</button></article>)}
    <form onChange={() => onDirty(true)} onSubmit={e => { e.preventDefault(); void run(async () => { const grant = await api<Grant>(base + `/grants/${selected}`, { method: 'PUT', body: { canUpload: upload, canAddLog: log } }); setGrants(old => [...old.filter(item => item.userId !== grant.userId), grant]); setSelected(''); setUpload(false); setLog(false); onDirty(false); }); }}><fieldset disabled={busy}><legend>{t('Grant or update record access', 'Παραχώρηση ή ενημέρωση πρόσβασης εγγραφής')}</legend><Field label={t('User', 'Χρήστης')}><select required value={selected} onChange={e => { setSelected(e.target.value); const grant = grants.find(item => item.userId === Number(e.target.value)); setUpload(grant?.canUpload ?? false); setLog(grant?.canAddLog ?? false); }}><option value="">{t('Choose', 'Επιλέξτε')}</option>{people.filter(person => person.active).map(person => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></Field><label><input type="checkbox" checked={upload} onChange={e => setUpload(e.target.checked)} />{t('Upload photos and attachments', 'Μεταφόρτωση φωτογραφιών και συνημμένων')}</label><label><input type="checkbox" checked={log} onChange={e => setLog(e.target.checked)} />{t('Add Log entries', 'Προσθήκη καταχωρίσεων στο ημερολόγιο')}</label><BusyButton type="submit" busy={busy}>{t('Save access', 'Αποθήκευση πρόσβασης')}</BusyButton></fieldset></form>
  </section>;
}
