import { useEffect, useState } from 'react';
import type { RecordList as ListData } from '../../server/records/list';
import type { LocationNode } from '../../server/lists/locations';
import { entriesOf, isCode, labelOf, type ListKey } from '../../domain';
import { api } from '../core/api';
import { useI18n } from '../core/i18n';
import { ErrorNotice, Field, MultiPick } from '../core/forms';
import { LocationPicker } from '../core/LocationPicker';
import { Capture } from './Capture';
type Named = { id: number; name?: string; nameEn?: string; nameEl?: string; active?: boolean };
export function RecordList({ projectId }: { projectId: number }) {
  const { lang, t } = useI18n(); const [data, setData] = useState<ListData | null>(null); const [error, setError] = useState<unknown>(null); const [capture, setCapture] = useState(false);
  const [allRecords, setAllRecords] = useState<ListData['records']>([]);
  const [lists, setLists] = useState<Record<string, Named[]>>({}); const [nodes, setNodes] = useState<LocationNode[]>([]);
  const [query, setQuery] = useState(() => new URLSearchParams(location.search)); const [applied, setApplied] = useState(location.search);
  const name = (item: Partial<Named>) => item.name ?? (lang === 'el' ? item.nameEl || item.nameEn : item.nameEn || item.nameEl) ?? '';
  useEffect(() => { const abort = new AbortController(); Promise.all(['people', 'trades', 'tags', 'zone-types', 'locations'].map(async kind => [kind, await api<Named[]>(`/api/projects/${projectId}/${kind}`, { signal: abort.signal })] as const)).then(result => { setLists(Object.fromEntries(result)); setNodes(Object.fromEntries(result).locations as LocationNode[]); }).catch(failure => { if (!abort.signal.aborted) setError(failure); }); return () => abort.abort(); }, [projectId]);
  useEffect(() => { const abort = new AbortController(); setData(null); setError(null); api<ListData>(`/api/projects/${projectId}/records${applied}`, { signal: abort.signal }).then(setData).catch(failure => { if (!abort.signal.aborted) setError(failure); }); return () => abort.abort(); }, [projectId, applied]);
  useEffect(() => { const abort = new AbortController(); api<ListData>(`/api/projects/${projectId}/records`, { signal: abort.signal }).then(result => setAllRecords(result.records)).catch(failure => { if (!abort.signal.aborted) setError(failure); }); return () => abort.abort(); }, [projectId]);
  const set = (key: string, value: string) => setQuery(previous => { const next = new URLSearchParams(previous); if (value) next.set(key, value); else next.delete(key); return next; });
  const fixed = (key: string, vocabulary: ListKey, label: string) => <Field label={label}><select multiple value={(query.get(key) ?? '').split(',').filter(Boolean)} onChange={event => set(key, Array.from(event.target.selectedOptions, option => option.value).join(','))}>{entriesOf(vocabulary).map(entry => <option key={entry.code} value={entry.code}>{labelOf(vocabulary, entry.code, lang)}</option>)}</select></Field>;
  const managed = (key: string, list: string, label: string) => <MultiPick label={label} items={(lists[list] ?? []).map(item => ({ id: item.id, label: name(item) }))} value={(query.get(key) ?? '').split(',').filter(Boolean).map(Number)} onChange={ids => set(key, ids.join(','))}/>;
  const filterLabels: Record<string, string> = { q: t('Search', 'Αναζήτηση'), subtype: t('Subtype', 'Υποκατηγορία'), status: t('Status', 'Κατάσταση'), priority: t('Priority', 'Προτεραιότητα'), severity: t('Severity', 'Σοβαρότητα'), stage: t('Stage', 'Στάδιο'), problemType: t('Type of problem', 'Είδος προβλήματος'), tradeId: t('Trade', 'Ειδικότητα'), tagId: t('Tag', 'Ετικέτα'), zoneTypeId: t('Zone type', 'Τύπος χώρου'), ballInCourtId: t('Next action by', 'Επόμενη ενέργεια από'), responsibleId: t('Responsible', 'Υπεύθυνος'), locationId: t('Location', 'Θέση'), safety: t('Safety', 'Ασφάλεια'), outsideScope: t('Outside contract', 'Εκτός σύμβασης'), blocking: t('Unfinished prerequisites', 'Ανολοκλήρωτες προαπαιτούμενες εργασίες'), dueFrom: t('Due from', 'Προθεσμία από'), dueTo: t('Due to', 'Προθεσμία έως'), before: t('Must be done before', 'Να γίνει πριν'), after: t('Requires first', 'Απαιτείται πρώτα') };
  const filterValue = (key: string, raw: string) => {
    const vocabs: Record<string, ListKey> = { subtype: 'subtype', status: 'status', priority: 'priority', severity: 'severity', stage: 'stage', problemType: 'problemType' };
    const managedKeys: Record<string, string> = { tradeId: 'trades', tagId: 'tags', zoneTypeId: 'zone-types', ballInCourtId: 'people', responsibleId: 'people', locationId: 'locations' };
    if (vocabs[key]) return raw.split(',').map(value => isCode(vocabs[key]!, value) ? labelOf(vocabs[key]!, value, lang) : t('Invalid filter', 'Μη έγκυρο φίλτρο')).join(', ');
    if (managedKeys[key]) return raw.split(',').map(value => name((key === 'locationId' ? nodes : lists[managedKeys[key]!] ?? []).find(item => item.id === Number(value)) ?? {})).join(', ');
    if (['safety', 'outsideScope', 'blocking'].includes(key)) return raw === 'true' ? t('Yes', 'Ναι') : t('No', 'Όχι');
    if (key === 'before' || key === 'after') return allRecords.find(record => record.id === Number(raw))?.humanId ?? t('Record', 'Καταγραφή');
    return raw;
  };
  return <><div className="title-row"><h1>{t('Records', 'Καταγραφές')}</h1><button className="primary" disabled={capture} onClick={() => setCapture(true)}>{t('New record', 'Νέα καταγραφή')}</button></div>{capture && <Capture projectId={projectId} nodes={nodes} onClose={() => { setCapture(false); location.reload(); }}/>}<form className="filters" onSubmit={event => { event.preventDefault(); const next = query.size ? `?${query}` : ''; history.replaceState(null, '', `${location.pathname}${next}`); setApplied(next); }}>
  <div className="grid"><Field label={t('Search title, description or ID', 'Αναζήτηση τίτλου, περιγραφής ή κωδικού')}><input type="search" value={query.get('q') ?? ''} maxLength={200} onChange={event => set('q', event.target.value)}/></Field><Field label={t('Sort', 'Ταξινόμηση')}><select value={query.get('sort') ?? 'id'} onChange={event => set('sort', event.target.value)}>{[['id', t('ID', 'Κωδικός')], ['due', t('Due date', 'Προθεσμία')], ['priority', t('Priority', 'Προτεραιότητα')], ['severity', t('Severity', 'Σοβαρότητα')], ['updated', t('Last updated', 'Τελευταία ενημέρωση')]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label={t('Order', 'Σειρά')}><select value={query.get('dir') ?? ''} onChange={event => set('dir', event.target.value)}><option value="">{t('Default', 'Προεπιλογή')}</option><option value="asc">{t('Ascending', 'Αύξουσα')}</option><option value="desc">{t('Descending', 'Φθίνουσα')}</option></select></Field></div>
  <details><summary>{t('Filters', 'Φίλτρα')}{query.size > 0 && ` (${query.size})`}</summary><div className="grid">{fixed('subtype', 'subtype', t('Subtype', 'Υποκατηγορία'))}{fixed('status', 'status', t('Status', 'Κατάσταση'))}{fixed('priority', 'priority', t('Priority', 'Προτεραιότητα'))}{fixed('severity', 'severity', t('Severity', 'Σοβαρότητα'))}{fixed('stage', 'stage', t('Stage', 'Στάδιο'))}{fixed('problemType', 'problemType', t('Type of problem', 'Είδος προβλήματος'))}
  {managed('tradeId', 'trades', t('Trades', 'Ειδικότητες'))}{managed('tagId', 'tags', t('Tags', 'Ετικέτες'))}{managed('zoneTypeId', 'zone-types', t('Zone type', 'Τύπος χώρου'))}{managed('ballInCourtId', 'people', t('Next action by', 'Επόμενη ενέργεια από'))}{managed('responsibleId', 'people', t('Responsible', 'Υπεύθυνος'))}
  <LocationPicker allowInactive nodes={nodes} value={(query.get('locationId') ?? '').split(',').filter(Boolean).map(Number)} onChange={ids => set('locationId', ids.join(','))}/>{[['safety', t('Safety implications', 'Θέμα ασφαλείας')], ['outsideScope', t('Outside contract scope', 'Εκτός σύμβασης')], ['blocking', t('Unfinished prerequisites', 'Ανολοκλήρωτες προαπαιτούμενες εργασίες')]].map(([key, label]) => <Field key={key} label={label!}><select value={query.get(key!) ?? ''} onChange={event => set(key!, event.target.value)}><option value="">{t('Any', 'Όλα')}</option><option value="true">{t('Yes', 'Ναι')}</option><option value="false">{t('No', 'Όχι')}</option></select></Field>)}{[['dueFrom', t('Due from', 'Προθεσμία από')], ['dueTo', t('Due to', 'Προθεσμία έως')]].map(([key, label]) => <Field key={key} label={label!}><input type="date" value={query.get(key!) ?? ''} onChange={event => set(key!, event.target.value)}/></Field>)}
  {(['before', 'after'] as const).map(key => <Field key={key} label={key === 'before' ? t('Must be done before', 'Να γίνει πριν') : t('Requires first', 'Απαιτείται πρώτα')}><select value={query.get(key) ?? ''} onChange={event => set(key, event.target.value)}><option value="">{t('Any record', 'Οποιαδήποτε καταγραφή')}</option>{allRecords.map(record => <option key={record.id} value={record.id}>{record.humanId} · {record.title}</option>)}</select></Field>)}
  </div></details><div className="actions"><button className="primary">{t('Apply', 'Εφαρμογή')}</button><button type="button" onClick={() => { setQuery(new URLSearchParams()); setApplied(''); history.replaceState(null, '', location.pathname); }}>{t('Clear filters', 'Καθαρισμός φίλτρων')}</button></div></form><div className="filter-chips">{[...new URLSearchParams(applied)].filter(([key]) => filterLabels[key]).map(([key, value]) => <button key={key} type="button" aria-label={`${t('Remove filter', 'Αφαίρεση φίλτρου')}: ${filterLabels[key]}`} onClick={() => { const next = new URLSearchParams(applied); next.delete(key); const search = next.size ? `?${next}` : ''; setQuery(next); setApplied(search); history.replaceState(null, '', location.pathname + search); }}>{filterLabels[key]}: {filterValue(key, value)} ×</button>)}</div><ErrorNotice error={error}/>
  {data && <><p className="totals">{data.totals.count} {t('records', 'καταγραφές')} · {t('Estimated extras (owner only)', 'Εκτιμώμενα πρόσθετα (μόνο ιδιοκτήτης)')}: {new Intl.NumberFormat(lang, { style: 'currency', currency: 'EUR' }).format(data.totals.estimatedCost)}</p><div className="record-list">{data.records.map(record => <article className="record-card" key={record.id}><a href={`/projects/${projectId}/records/${record.id}?from=${encodeURIComponent(applied)}`}><strong>{record.humanId}</strong><h2>{record.title || t('Untitled draft', 'Πρόχειρο χωρίς τίτλο')}</h2></a><div className="record-facts"><span>{labelOf('subtype', record.subtype, lang)}</span><span className="badge">{labelOf('status', record.status, lang)}</span><span>{t('Next action by', 'Επόμενη ενέργεια από')}: {name((lists.people ?? []).find(item => item.id === record.ballInCourtId) ?? {}) || '—'}</span><span>{t('Due', 'Προθεσμία')}: {record.dueDate ?? '—'}</span><span>{t('Priority', 'Προτεραιότητα')}: {record.priority ? labelOf('priority', record.priority, lang) : '—'}</span><span>{t('Severity', 'Σοβαρότητα')}: {record.severity ? labelOf('severity', record.severity, lang) : '—'}</span>{record.completion !== null && <label>{t('Completion', 'Ολοκλήρωση')} <progress max={100} value={record.completion}/> {record.completion}%</label>}{record.safety && <span className="safety">{t('Safety implications', 'Θέμα ασφαλείας')}</span>}</div></article>)}</div>{data.records.length === 0 && <p>{t('No matching records.', 'Δεν βρέθηκαν καταγραφές.')}</p>}</>}{!data && !error && <p role="status">{t('Loading…', 'Φόρτωση…')}</p>}</>;
}
